[gspread]
type = "service_account"
project_id = "grasacorporalapp"
private_key_id = "b010382942ac21a4d99ec0a1391c8f84d9f78826"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2ju5rMMzRl5qd
pyyL5V8YC0EIYzBjqrNuAtBkrPgHS4Yl5KvwcwvcCnSH/fXMASAT3sd6ne0AU42C
qL8QY5rbsVdi7ApYDBHXKxGqkPFo+xgZaEpVIumlxkK4p96K1JDWDformJLa8f2e
xi4SFNzcSPVqWmGfnKNTZv1tjoT97QweAyCOHGCWbli/i9oUO99CBOCOYA1RrbCH
az6xfKsldGrFfFD/WUaEsQP+owWjFdQuqwmCRiOyAjR7xxKGDt44ggzPlBzOFSCL
mUJST86Jk26f5/FwaSi/9zNgrZGoFD+i8LwtJMaS0zn/VuMryu9rhLEvDhwQXNXi
wBw8/hZPAgMBAAECggEABDEn1P4W+r2C90zMvCrYfxC/F3MdPAsO7Ljga5EA1W+m
btdStWytRvCJUktPUILUGqPnRVY8CEf8fC9L/kamc/xqBJaYx2kB8RFtnR+P7Su0
fXZ3tbKQ1lXFPkB1XtwlT60DFur9fRnI2G0CxzdQbQSF3vSgjXQ6ceKJcXF83Bto
nZI06DJp/sAiWaKV9Pf69uYKBiorCPqa7ZxXbUZob/eMfLrsFwXD92IkibZfLz4x
UBG8hwlMDglOTsHvNKTiMvPdLQ3qxZ1LIwb2brGWORfUiu2+ekz+KKCZh4Iil8XA
SMIlRhK9bOZZYLkCVUjGh+P1uDADxDb+BBL39j0XHQKBgQD++DJBtyMQICf9Wn5Y
Il6IxtQqp3UFcKjOAkrpjNZIM9qwgeTBiWQ3vkMk70tjBq+sxbF+QBudqtBKrcDU
c5FVVnl9fSVIj/QbPTtTkyURv3h8OmEWJ9W7OWlRIfh9mFVixcokRyPQA7gI87mQ
Wawc5UwrZ5pPzQCR/qX9mBHk3QKBgQC3S9CeeBlzGkYaCxeLphucHHjMuvIbgHUO
CB3teYeGuOwARK3byC3x2RJhzD+31pkPBcqt0AjTeVRAT/tlSVYCtdPwjeeniDw2
dvSbVO3rgV+uwBz2HpBA76OL2B6Uu25bSeolwDPpXl+um+wB4hNJSNip0UvC+FTc
MnUw5VoPGwKBgCwWNnpudD2hkciZESekKbx0xNLrSay7IjUc6F8h3xt0++dxTmC4
pP+OgoWsatigm1fAh0RRSXUlyAZhrOoPYZ3j6fXs4bl+SrM7DzsQQmSjOu4gGhF+
qdJJxxAkU5dD89+0W5OSSXr6aaQCoJ95Ie2NKHKI44HQ7LxRz9ndpZpxAoGARYPs
V91mkX+6bHAeeukBeaBWtBaGcaWzPyIW75RysMZ7QtLJORxfSGSyEwMae0dY/xiM
OIU4g7N1H3r19gDtLNP20DmRTLlfVKyisjJwlSuYtTbJBRKsVORNm2DYoEHBZb/P
nIebaHtRQHCD/mbWN6n3+deVqxjxXh2I0oV5NVcCgYEA5Z4rGQfs1Zd1PGCcXpO1
Ljq+GAlDGcbarM9uPiiWVERKRilevlvz+YPJlzrLYN0UY7uV5BbuI3FiX9YyL/z6
xDI+mZ4aCtzCcSBm/r05WE7i3nrETeRcCHW1TtrHwgfiQFcAoLgdVb1BFyTYu34T
w3KEvdMP1YArrv4kn9FvPoA=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets@grasacorporalapp.iam.gserviceaccount.com"
client_id = "114370300656376638797"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets@grasacorporalapp.iam.gserviceaccount.com"
universe_domain = "googleapis.com"